### PR TITLE
Use ksni on linux

### PR DESCRIPTION
**Pull request by njust**
Hi, I updated the linux implementation to use ksni as discussed in [#2](https://github.com/olback/tray-item-rs/issues/2). I tested it on linux Mint 20.1.

### CODE REVIEW

**Comment by olback** [comment]
Hi, I'd like to see the old implementation still available under a feature flag since ksni does not work in all environments.

**Comment by ancwrd1** [comment]
Doesn't libappindicator use the same dbus SNI interface internally to show the tray icon?
@olback could you give an example where it won't work?

**Comment by olback** [comment]
@ancwrd1 It does not work when using Waybar. 

Old impl:


New impl:


Well, it does *work* but the icon is missing, space is allocated, hint and click actions work just fine.

Sorry for the extremely late reply.

**Comment by olback** [comment]
Version `0.8.0` is now released and supports both `ksni` and `libappindicator`.

**Pull request closed without merging**
